/**
 * build.mjs — dsh-html-ui v1.0.0 构建链。
 *
 * 输入（真相源）：src/**（ESM，零运行时依赖）
 * 产物：
 *   dsh-html-client.js                页面级 IIFE（入口，禁手改；页面注入形态）
 *   bundle/lib/client.js              ModuleLoader 包装（L3 + L2 + L1）
 *   bundle/lib/index.js               host 半边（PromptSection + skill + KaTeX 路由）
 *   bundle/lib/assets/katex/**        KaTeX 引擎 + 字体（复用旧版资产）
 *   bundle/skills/dsh-html-ui/SKILL.md
 *   bundle/package.json / cordis.patch.yml / README.md
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, copyFileSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSync } from 'esbuild'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const bundleDir = join(root, 'bundle')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const version = pkg.version

/* 1. 页面级 IIFE（页面注入形态，保留入口行为） */
const iife = buildSync({
  entryPoints: [join(root, 'src', 'entry.js')],
  bundle: true, format: 'iife',
  target: ['chrome120', 'firefox121', 'safari17'],
  write: false, minify: false, legalComments: 'inline', logLevel: 'silent',
})
writeFileSync(join(root, 'dsh-html-client.js'), iife.outputFiles[0].text)

/* 2. bundle 组装 */
rmSync(bundleDir, { recursive: true, force: true })
mkdirSync(join(bundleDir, 'lib', 'assets', 'katex', 'fonts'), { recursive: true })
mkdirSync(join(bundleDir, 'skills', 'dsh-html-ui'), { recursive: true })

/* 2.1 client half */
const clientBundle = buildSync({
  entryPoints: [join(root, 'src', 'client-wrapper.js')],
  bundle: true, format: 'iife',
  target: ['chrome120', 'firefox121', 'safari17'],
  write: false, minify: false, legalComments: 'inline', logLevel: 'silent',
})
writeFileSync(join(bundleDir, 'lib', 'client.js'), clientBundle.outputFiles[0].text)

/* 2.2 host half（模板；PromptSection order 106 惯例位） */
const indexJs = `/**
 * dsh-html-ui — host half (v1.0.0, generated by tools/build.mjs — do not edit).
 *
 * Registers:
 *  1. a webserver prefix route serving the KaTeX engine/fonts (immutable cache);
 *  2. a system-prompt section teaching the html/dsh-html fence contract (order 106);
 *  3. a bundled skill (skills/dsh-html-ui/SKILL.md).
 */
import { readFileSync, existsSync } from "node:fs";
import { join, dirname, normalize } from "node:path";
import { fileURLToPath } from "node:url";

const F3 = String.fromCharCode(96, 96, 96);
const ASSET_ROUTE_PATH = "/plugins/dsh-html-ui/assets";
const ALLOWED_RE = /\\.(js|css|woff2|json)$/;
const MIME = {
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".woff2": "font/woff2",
  ".json": "application/json; charset=utf-8",
};

const here = dirname(fileURLToPath(import.meta.url));
const assetDir = join(here, "assets", "katex");

async function serveAsset(req, res) {
  if (req.method !== "GET" && req.method !== "HEAD") { res.writeHead(405); res.end(); return }
  let pathname
  try { pathname = decodeURIComponent(new URL(req.url ?? "/", "http://x").pathname) }
  catch { res.writeHead(400); res.end(); return }
  const prefix = ASSET_ROUTE_PATH + "/katex/"
  if (!pathname.startsWith(prefix)) { res.writeHead(404); res.end(); return }
  const rel = pathname.slice(prefix.length)
  const file = normalize(rel)
  if (file.startsWith("..") || !ALLOWED_RE.test(file)) { res.writeHead(404); res.end(); return }
  const full = join(assetDir, file)
  if (!full.startsWith(assetDir) || !existsSync(full)) { res.writeHead(404); res.end(); return }
  try {
    const body = readFileSync(full)
    res.writeHead(200, {
      "content-type": MIME[file.slice(file.lastIndexOf("."))] || "application/octet-stream",
      "cache-control": "public, max-age=31536000, immutable",
    })
    res.end(body)
  } catch { res.writeHead(404); res.end() }
}

const SECTION_TEXT = [
  "你可以用 " + F3 + "html 围栏（或 " + F3 + "dsh-html 围栏）输出任意原始 HTML，由渲染器在聊天流内联渲染（样式/本地交互脚本/块级 KaTeX 公式全支持，无边框融入对话流）。",
  "触发：结构图/流程图、多卡讲义、对照大表、计算卡、交互小部件、整页交付物等纯文字难以表达的内容 —— 命中即用；普通问答/短答/公式推导仍用 Markdown。",
  "每个围栏是独立文档：自带精简 <style>（半透明中性底，不写死背景/文字色）；脚本仅围栏内本地交互（禁网络/禁 iframe/禁父页）；块级公式写 $$…$$（行内 $ 不渲染，金额请直接写数字）；红字用 <mark>。",
  "图片优先内联 SVG（外链图片默认不渲染）；沙箱会静默阻断 alert/confirm/prompt、表单提交、弹窗、localStorage —— 反馈一律用页内 DOM 呈现。",
  "限额：≤3 围栏/回合、各 ≤250 行；整页交付物单围栏 ≤500 行、≤1MB。",
].join("\\n");

const bundledSkillPath = join(here, "..", "skills", "dsh-html-ui", "SKILL.md");
const SKILL_PROVIDER = "dsh-html-ui";
const SKILL_DESCRIPTION = "dsh-html 围栏输出协议：触发判定、样式库、安全红线与限额。";

function bundledSkillProvider() {
  const raw = existsSync(bundledSkillPath) ? readFileSync(bundledSkillPath, "utf8") : "";
  const end = raw.indexOf("---", 4);
  const meta = {
    name: "dsh-html-ui",
    description: SKILL_DESCRIPTION,
    invocation: { modelInvocable: true, userInvocable: true },
    source: "bundled",
    provider: SKILL_PROVIDER,
    path: bundledSkillPath,
    resourceBase: { kind: "directory", path: dirname(bundledSkillPath) },
    rank: 600,
    locator: bundledSkillPath,
  };
  return {
    name: SKILL_PROVIDER,
    list: () => Promise.resolve(end >= 0 ? [meta] : []),
    get: () => Promise.resolve(Object.assign({}, meta, { content: end >= 0 ? raw.slice(end + 5) : raw })),
  };
}

const inject = ["systemPrompt"];

function apply(ctx) {
  ctx.effect(() => {
    ctx.systemPrompt.section({
      name: "dsh-html-ui:fence",
      order: 106,
      text: SECTION_TEXT,
    });
  }, "dsh-html-ui.systemPrompt.section()");
  ctx.inject(["skills"], (skillCtx) => {
    skillCtx.skills.registerProvider(() => bundledSkillProvider());
  });
  let assetsRegistered = false;
  const tryRegisterAssets = (value) => {
    if (assetsRegistered) return;
    const webServer = value ?? ctx.reflect.get("webServer", false);
    if (webServer === void 0) return;
    webServer.register({ kind: "prefix", path: ASSET_ROUTE_PATH, handler: serveAsset });
    assetsRegistered = true;
  };
  tryRegisterAssets(void 0);
  ctx.on("internal/service", (name, value) => {
    if (name === "webServer") tryRegisterAssets(value);
  });
}

export { SECTION_TEXT, apply, inject };
`
writeFileSync(join(bundleDir, 'lib', 'index.js'), indexJs)

/* 2.3 bundle package.json（F10：inject 最小化 —— 空注入，全部可选） */
writeFileSync(join(bundleDir, 'package.json'), JSON.stringify({
  name: 'dsh-html-ui',
  description: 'Inline HTML + KaTeX renderer for DeepSeek Harness (DSH) chats — deterministic fence takeover, event-driven height, zero-CPU idle, sandboxed iframes. Install: dsh plugin --profile web add dsh-html-ui',
  version,
  license: 'MIT',
  type: 'module',
  main: './lib/index.js',
  repository: { type: 'git', url: 'git+https://github.com/zgxaxdd/dsh-html-ui.git' },
  exports: {
    '.': './lib/index.js',
    './client': './lib/client.js',
  },
  dsh: {
    bundle: { patch: './cordis.patch.yml' },
    client: { platform: 'web', immediately: true, inject: [] },
  },
  scripts: {
    prepublishOnly: 'cd .. && npm run check && npm run build:bundle',
  },
  files: ['lib', 'skills', 'cordis.patch.yml', 'README.md'],
  keywords: ['dsh', 'dsh-plugin', 'deepseek', 'katex', 'html-renderer', 'sandbox'],
}, null, 2))

/* 2.4 cordis.patch.yml */
writeFileSync(join(bundleDir, 'cordis.patch.yml'), `# dsh-html-ui bundle for DeepSeek Harness (dsh).
# Installed via: dsh plugin --profile web add dsh-html-ui
- insert:
    - id: ui-dsh-html-ui
      name: 'dsh-html-ui'
`)

/* 2.5 KaTeX assets（复用旧版 dsh-html-render 资产，含 SHA256SUMS 基建） */
copyDir(join(root, 'vendor', 'katex'), join(bundleDir, 'lib', 'assets', 'katex'))
/* 生成 data-URI 内联字体版 CSS：满足 iframe CSP font-src data:（F7 零外网） */
buildKatexInlineCss(join(bundleDir, 'lib', 'assets', 'katex'))
copyFileSync(join(root, 'skills', 'dsh-html-ui', 'SKILL.md'), join(bundleDir, 'skills', 'dsh-html-ui', 'SKILL.md'))

/* 将 katex.min.css 的 fonts/ 引用替换为 data: 内联字体（构建期，零运行时外网）。
 * 每字体三种格式（woff2/woff/ttf）：woff2 是首选，但为杜绝 iframe 内
 * CSP font-src data: 的任何告警，三种格式全部内联（浏览器只取第一个可用）。 */
function buildKatexInlineCss(katexDir) {
  const cssPath = join(katexDir, 'katex.min.css')
  if (!existsSync(cssPath)) { console.warn('katex.min.css missing; skip inline css'); return }
  let css = readFileSync(cssPath, 'utf8')
  css = css.replace(/url\(["']?fonts\/([^)"']+)["']?\)/g, (m, name) => {
    const fontPath = join(katexDir, 'fonts', name)
    if (!existsSync(fontPath)) return m
    const ext = name.slice(name.lastIndexOf('.'))
    const mime = ext === '.woff2' ? 'font/woff2' : ext === '.woff' ? 'font/woff' : 'font/ttf'
    const b64 = readFileSync(fontPath).toString('base64')
    return `url(data:${mime};base64,${b64})`
  })
  /* 删除仍指向 fonts/ 的 fallback（vendor 只有 woff2；woff/ttf 引用无文件，
   * 浏览器也不会请求——但为避免任何潜在 CSP 告警，整段 url+format 删掉） */
  css = css.replace(/url\(["']?fonts\/[^)"']+["']?\)\s*format\([^)]*\)\s*,?/g, '')
  /* 若 src 只剩一个 data: 项，结尾可能残留逗号 → 归一 */
  css = css.replace(/src:(data:[^;]*),?\}/g, 'src:$1}')
  writeFileSync(join(katexDir, 'katex.inline.css'), css)
  const remaining = (css.match(/url\([^)]*fonts\//g) || []).length
  console.log(`  katex.inline.css   (${Math.round(css.length / 1024)} KB, fonts inlined; remaining refs: ${remaining})`)
}

/* 2.6 bundle README */
writeFileSync(join(bundleDir, 'README.md'), `# dsh-html-ui（DSH profile bundle）

由仓库根 \`tools/build.mjs\` 生成，请勿手改。

\`\`\`sh
dsh plugin --profile web add dsh-html-ui
dsh plugin --profile web add link:<本目录绝对路径>
\`\`\`

- Host 半边（lib/index.js）：KaTeX 资产路由（immutable）+ systemPrompt 围栏契约 + 打包 skill
- Client 半边（lib/client.js）：ModuleLoader 包装（v${version}，inject 最小化，全可选）
- 卸载：\`dsh plugin --profile web remove dsh-html-ui\`
`)

function copyDir(src, dst) {
  mkdirSync(dst, { recursive: true })
  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const s = join(src, entry.name)
    const d = join(dst, entry.name)
    if (entry.isDirectory()) copyDir(s, d)
    else copyFileSync(s, d)
  }
}

console.log(`v${version} build -> ${bundleDir}`)
console.log(`  dsh-html-client.js  (${Math.round(statSize(join(root, 'dsh-html-client.js')) / 1024)} KB)`)
console.log(`  lib/client.js       (${Math.round(statSize(join(bundleDir, 'lib', 'client.js')) / 1024)} KB)`)
console.log(`  lib/assets/katex    (${countFiles(join(bundleDir, 'lib', 'assets', 'katex'))} files)`)

function statSize(p) { return existsSync(p) ? readFileSync(p).length : 0 }
function countFiles(dir) {
  let n = 0
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) n += countFiles(join(dir, e.name))
    else n++
  }
  return n
}
